WITH UnionCTE AS (
  SELECT 
    SALES_ORDER_ID, LINE_ID, PRODUCTSEGMENT, PRODUCTSUBSEGMENT, PRODUCTDESCRIPTION, 
    PRODUCTINITIATIVE, SHIP_DATE, QUANTITY, PRICE, PRICELINEDESCRIPTION, 
    BUYLINEDESCRIPTION, YEAR 
  FROM JS2023
  WHERE PRODUCTSEGMENT = 'PARTS'

  UNION

  SELECT 
    SALES_ORDER_ID, LINE_ID, PRODUCTSEGMENT, PRODUCTSUBSEGMENT, PRODUCTDESCRIPTION, 
    PRODUCTINITIATIVE, SHIP_DATE, QUANTITY, PRICE, PRICELINEDESCRIPTION, 
    BUYLINEDESCRIPTION, YEAR 
  FROM JS2022
  WHERE PRODUCTSEGMENT = 'PARTS'
);
